from app.models.user import User
from app.models.student import Student
from app.models.company import Company
from app.models.internship import Internship
from app.models.application import Application
from app.models.review import Review
from app.models.saved_internship import SavedInternship
from app.models.message import Message
from app.models.cv_analysis import CvAnalysis